version: "3.2"

services:
  postgres:
    image: postgres:13.0-alpine
    environment:
      POSTGRES_DB: cohostdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    restart: "always"
    volumes:
      - cohost_postgres_db:/var/lib/postgresql/data

volumes:
  cohost_postgres_db:
